name: drupaltest
registries:
ship_defaults:
  timeout: 60
ships:
  node1: 
    ip: 10.132.187.57
    docker_port: 2375
  node2:
    ip: 10.132.219.180
    docker_port: 2375
services:
  web:
    image: luis/drupaltest
    instances:
      i1:
        ship: node1
        ports: {web: 80}
        env:
          SERVICE_NAME: app
          SERVICE_TAGS: production
      i2:
        ship: node2
        ports: {web: 80}
        env:
          SERVICE_NAME: app
          SERVICE_TAGS: production
